from __future__ import annotations

SCHEMA_VERSION = "1"
DEFAULT_DB_FILENAME = "sanitizer_cases.sqlite"

KNOWN_SOURCE_TYPES = {
    "custom",
    "official_or_framework",
    "third_party_library",
    "policy_or_rule",
    "mixed",
    "uncertain",
}

LANGUAGE_ALIASES = {
    "c": "c",
    "c++": "c++",
    "cpp": "c++",
    "c#": "c#",
    "csharp": "c#",
    "dotnet": "c#",
    "go": "go",
    "golang": "go",
    "java": "java",
    "javascript": "javascript",
    "js": "javascript",
    "node": "javascript",
    "nodejs": "javascript",
    "php": "php",
    "python": "python",
    "py": "python",
    "ruby": "ruby",
    "rb": "ruby",
    "rust": "rust",
    "swift": "swift",
    "ts": "typescript",
    "tsx": "typescript",
    "typescript": "typescript",
}

SOURCE_TYPE_ALIASES = {
    "custom": "custom",
    "framework": "official_or_framework",
    "official": "official_or_framework",
    "official_or_framework": "official_or_framework",
    "third_party": "third_party_library",
    "third-party": "third_party_library",
    "third_party_library": "third_party_library",
    "library": "third_party_library",
    "policy": "policy_or_rule",
    "rule": "policy_or_rule",
    "policy_or_rule": "policy_or_rule",
    "mixed": "mixed",
    "uncertain": "uncertain",
}

ATTACK_SURFACE_PATTERNS = {
    "command_injection": [
        "command injection",
        "os command",
        "shell injection",
        "shell metacharacter",
        "cmd injection",
        "rce",
        "命令注入",
        "shell",
        "exec",
    ],
    "file_upload": [
        "file upload",
        "upload",
        "uploaded file",
        "mime type",
        "dangerous file",
        "文件上传",
        "上传",
        "扩展名",
        "mime",
    ],
    "open_redirect": [
        "open redirect",
        "redirect",
        "url redirect",
        "重定向",
    ],
    "path_traversal": [
        "path traversal",
        "directory traversal",
        "zip slip",
        "路径遍历",
        "目录遍历",
        "../",
    ],
    "sqli": [
        "sql injection",
        "sqli",
        "sql query",
        "order by",
        "like clause",
        "sql注入",
        "数据库查询",
    ],
    "ssrf": [
        "ssrf",
        "server-side request forgery",
        "服务端请求伪造",
    ],
    "template_injection": [
        "template injection",
        "ssti",
        "模板注入",
    ],
    "xss": [
        "xss",
        "cross-site scripting",
        "stored xss",
        "reflected xss",
        "跨站脚本",
        "script 注入",
        "<script",
        "javascript:",
        "html attribute",
    ],
    "xxe": [
        "xxe",
        "xml external entity",
        "外部实体",
    ],
}

DEFENSE_MECHANISM_PATTERNS = {
    "blacklist": [
        "blacklist",
        "denylist",
        "forbidden character",
        "illegal character",
        "黑名单",
        "非法字符",
    ],
    "escape": [
        "escape",
        "escaping",
        "htmlspecialchars",
        "htmlentities",
        "addslashes",
        "escapehtml",
        "转义",
    ],
    "mime_policy": [
        "mime",
        "content-type",
        "nosniff",
        "media type",
        "文件类型",
        "mime type",
    ],
    "output_encoding": [
        "output encoding",
        "html encoding",
        "entity encoding",
        "实体编码",
        "编码输出",
    ],
    "path_rule": [
        "path rule",
        "path prefix",
        "path check",
        "prefix check",
        "路径规则",
        "路径前缀",
    ],
    "prepared_statement": [
        "prepared statement",
        "parameterized",
        "placeholder",
        "预编译",
        "占位符",
    ],
    "regex": [
        "regex",
        "regular expression",
        "preg_match",
        "pattern match",
        "正则",
        "模式匹配",
    ],
    "type_check": [
        "is_numeric",
        "type check",
        "type validation",
        "类型检查",
    ],
    "whitelist": [
        "whitelist",
        "allowlist",
        "allowed list",
        "in_array",
        "白名单",
        "允许列表",
    ],
}

FAILURE_MODE_PATTERNS = {
    "bad_blacklist": [
        "blacklist",
        "仅拦截",
        "只拦截",
        "黑名单",
        "forbidden character",
        "only checks",
    ],
    "context_mismatch": [
        "context mismatch",
        "wrong context",
        "attribute context",
        "javascript context",
        "html context",
        "上下文不匹配",
        "用于 js",
    ],
    "coverage_gap": [
        "coverage gap",
        "not cover",
        "uncovered",
        "遗漏",
        "漏掉",
        "覆盖不全",
        "部分字段",
        "部分参数",
    ],
    "missing_canonicalization": [
        "canonical",
        "normalize",
        "normalization",
        "leading whitespace",
        "反斜杠",
        "空白字符",
        "编码混淆",
        "decode",
    ],
    "parser_mismatch": [
        "parser",
        "browser compatibility",
        "svg",
        "xml",
        "finfo",
        "nosniff",
        "解析",
    ],
    "policy_gap": [
        "policy",
        "rule",
        "scope",
        "request type",
        "configuration",
        "白名单配置",
        "策略",
        "规则",
    ],
    "weak_regex": [
        "regex",
        "regular expression",
        "character class",
        "[a-z]",
        "[A-z]",
        "正则",
    ],
    "wrong_allowlist": [
        "allowlist",
        "whitelist",
        "white list",
        "dangerous type included",
        "白名单",
        "错误包含",
    ],
    "wrong_api_usage": [
        "misuse",
        "wrong api",
        "placeholder for table name",
        "escapexml=false",
        "htmlspecialchars() 处理 sql",
        "用于 sql",
        "用法不当",
        "误用",
    ],
}

QUERY_EXPANSIONS = {
    "blacklist": ["denylist", "forbidden character", "illegal character", "黑名单"],
    "command_injection": ["shell", "exec", "os command", "命令注入"],
    "context_mismatch": ["wrong context", "attribute context", "javascript context", "上下文不匹配"],
    "coverage_gap": ["uncovered", "覆盖不全", "遗漏"],
    "escape": ["htmlspecialchars", "htmlentities", "escapeHtml", "转义"],
    "file_upload": ["upload", "mime", "extension", "文件上传"],
    "mime_policy": ["content-type", "media type", "nosniff", "mime"],
    "open_redirect": ["redirect", "url", "重定向"],
    "output_encoding": ["html encoding", "entity encoding", "输出编码", "实体编码"],
    "path_traversal": ["directory traversal", "../", "路径遍历"],
    "policy_or_rule": ["policy", "rule", "scope", "策略", "规则"],
    "prepared_statement": ["placeholder", "parameterized", "预编译", "占位符"],
    "regex": ["regular expression", "pattern", "preg_match", "正则"],
    "sqli": ["sql injection", "sqli", "query", "sql注入"],
    "ssrf": ["server-side request forgery", "服务端请求伪造"],
    "whitelist": ["allowlist", "allowed list", "白名单"],
    "wrong_allowlist": ["dangerous type", "white list", "白名单"],
    "wrong_api_usage": ["misuse", "用法不当", "误用"],
    "xss": ["cross-site scripting", "html", "javascript:", "跨站脚本"],
}
